// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlyewtsU5mUSZaQBTu7XOU2Kr1Iqfdgsk',
    appId: '1:931321173775:web:6dadf887257cf6a5a6507a',
    messagingSenderId: '931321173775',
    projectId: 'fixnear-d84d4',
    authDomain: 'fixnear-d84d4.firebaseapp.com',
    storageBucket: 'fixnear-d84d4.firebasestorage.app',
    measurementId: 'G-40XBWZ7EDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5eJMoy_3fTOuCMyCH9gHKOV8CMwzL7GI',
    appId: '1:931321173775:android:51c46eca6cf65279a6507a',
    messagingSenderId: '931321173775',
    projectId: 'fixnear-d84d4',
    storageBucket: 'fixnear-d84d4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL2aqTXsT_2NeRCHL0e1sx5M3Tm1E7Xm0',
    appId: '1:931321173775:ios:23ded0bbf0757896a6507a',
    messagingSenderId: '931321173775',
    projectId: 'fixnear-d84d4',
    storageBucket: 'fixnear-d84d4.firebasestorage.app',
    iosBundleId: 'com.example.readyFixx',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL2aqTXsT_2NeRCHL0e1sx5M3Tm1E7Xm0',
    appId: '1:931321173775:ios:23ded0bbf0757896a6507a',
    messagingSenderId: '931321173775',
    projectId: 'fixnear-d84d4',
    storageBucket: 'fixnear-d84d4.firebasestorage.app',
    iosBundleId: 'com.example.readyFixx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlyewtsU5mUSZaQBTu7XOU2Kr1Iqfdgsk',
    appId: '1:931321173775:web:6ebe4ea1212e649ca6507a',
    messagingSenderId: '931321173775',
    projectId: 'fixnear-d84d4',
    authDomain: 'fixnear-d84d4.firebaseapp.com',
    storageBucket: 'fixnear-d84d4.firebasestorage.app',
    measurementId: 'G-THKHE3WTLE',
  );
}
